### ISSUE TITLE
Intronic variants not returning a conflict of reference base

### ISSUE THREAD

**Issue by ifokkema** [openvar/variantValidator#165]
When I send an [exonic variant with a mismatch with the reference base](https://www35.lamp.le.ac.uk/VariantValidator/variantvalidator/GRCh37/NM_007294.3%3Ac.5276G%3EA/all?content-type=application%2Fjson), I get a fatal error (VV warning) as I expect ("Variant reference (G) does not agree with reference sequence (A)"). However, if I do the same for an intronic variant, such as [NM_007294.3:c.5277+77G>A](https://www35.lamp.le.ac.uk/VariantValidator/variantvalidator/GRCh37/NM_007294.3%3Ac.5277%2B77G%3EA/all?content-type=application%2Fjson), I get no error, just a "silent" warning that the variant has been automapped to one using the proper reference base. "Silent" because the flag looks normal ("gene_variant") and normal output is provided, including protein change prediction and mappings to other genome builds. This makes it very hard for me to see the difference with [harmless automapping](https://www35.lamp.le.ac.uk/VariantValidator/variantvalidator/GRCh37/NM_007294.3%3Ac.5275del/all?content-type=application%2Fjson), and basically removes an easy method to check for variant errors.

Exerpt of relevant JSON with NM_007294.3:c.5277+77G>A as input:
```json
{
  "NM_007294.3:c.5277+77C>A": {
    "gene_symbol": "BRCA1",
    "genome_context_intronic_sequence": "NC_000017.10(NM_007294.3):c.5277+77C>A",
    "hgvs_transcript_variant": "NM_007294.3:c.5277+77C>A",
    "submitted_variant": "NM_007294.3:c.5277+77G>A",
    "validation_warnings": [
      "NM_007294.3:c.5277+77G>A automapped to NM_007294.3:c.5277+77C>A"
    ]
  },
  "flag": "gene_variant",
}
```

I understand that when I wouldn't provide a genomic reference sequence, you'd have to choose for me and probably don't want to throw a fatal warning when that doesn't work out well. But since VV requires a genome build, there shouldn't be an issue of which reference sequence to use, and I argue that a "variant reference (...) does not agree with (...)" is in place. What do you think?

**Comment by PeteCausey-Freeman** [comment]
We cannot necessarily assume this though because a RefSeq transcript can map to a chromosome, RefSeqGene, Alt loci, patches, etc, all of which can in theory be different. Therefore even if genome build is specified we cannot know the intended reference sequence, consequently the proposed error message could be inaccurate. However, I will grant that we do select the chromosomal alignment where possible, but in some instances this is not possible so again it is impossible to assume. Not sure to be honest. Unless a specific genomic reference sequence is provided the a hard warning could be inaccurate.

**Comment by ifokkema** [comment]
> We cannot necessarily assume this though because a RefSeq transcript can map to a chromosome, RefSeqGene, Alt loci, patches, etc, all of which can, in theory, be different. Therefore even if genome build is specified we cannot know the intended reference sequence, consequently, the proposed error message could be inaccurate.

Would it be OK to say that if users would want the variant mapped to any of those, they'd need to submit the variant as such? I mean, I can't even submit the variant as `NC_000017.10(NM_007294.3):c.5277+77G>A` because that still doesn't work. That leaves no space for assumptions, yet it just changes my variant :thinking: 

> Not sure to be honest. Unless a specific genomic reference sequence is provided a hard warning could be inaccurate.

If I would be required to pass the variant as `NC_000017.10(NM_007294.3):c.5277+77G>A`, that would be acceptable. Now I have no checks on intronic variants at all, which is, in my opinion, worse. :man_shrugging:

**Comment by PeteCausey-Freeman** [comment]
I agree that if we receive the full HGVS compliant description `NC_000017.10(NM_007294.3):c.5277+77G>A` then absolutely we should be able to accurately generate this validly. If that works for you I'll start on the code this afternoon. Yay!

I cannot agree that no checks on the reference bases at intronic positions in the context of transcript reference sequences is worse. There is no way to validly check this because the bases do not exist, so unless the intronic reference sequence is explicitly stated we make no assumptions. I have examples of variants that output different intronic bases for the RefSeq Gene and LRG and GRCh38, than they do for GRCh37. Which is correct????? VV makes no assumptions and outputs the correct variant description at each level. Personally I think your compromise is actually the correct way to go.

I think we should add some additional information to the user manuals around this. 

We should think about writing some of this stuff up Ivo :)

**Comment by ifokkema** [comment]
> I agree that if we receive the full HGVS compliant description `NC_000017.10(NM_007294.3):c.5277+77G>A` then absolutely we should be able to accurately generate this validly. If that works for you I'll start on the code this afternoon. Yay!

Great! Just to be sure, if I'd pass this format for an exonic variant, will still the NM sequence be used rather than the NC sequence? Just to be sure, because Mutalyzer uses the NC sequence for exonic variants in this case, and just uses the NM for the mapping of the given position. If needed, I could add code that checks for intronic positions and chooses the format to send.

> I cannot agree that no checks on the reference bases at intronic positions in the context of transcript reference sequences is worse. There is no way to validly check this because the bases do not exist, so unless the intronic reference sequence is explicitly stated we make no assumptions. I have examples of variants that output different intronic bases for the RefSeq Gene and LRG and GRCh38, than they do for GRCh37. Which is correct????? VV makes no assumptions and outputs the correct variant description at each level.

Playing the devil's advocate here, considering the last sentence... VV assumes here that I want the C>A variant while I passed G>A and outputs not a correct variant description, but some other variant, that I didn't want :wink:
It assumes the position is correct, and my reference base might not be.
Of course, my approach might be the complete opposite here; right now, I'm trying to actively find mistakes in the variants that we store, so I want everything thoroughly checked. Silent conversions of variants are super useful (ins to dup, 3' shifting, etc.), but in this case, it's a problem for me because this is undeniably a different variant - it is a translation of the genotype that I sent.

> I think we should add some additional information to the user manuals around this.

Great idea! This makes me think that perhaps also adding something like "If you do not wish this automapping to happen, pass the variant as NC ..." to the warning could be useful? :thinking: 

> We should think about writing some of this stuff up Ivo :)

We definitely should! I've also been thinking about writing out a thorough comparison between the different tools that exist (Mutalyzer, VV, VEP), as an extension of my previous student's work. That does require a lot more work, though.

**Comment by PeteCausey-Freeman** [comment]
> We definitely should! I've also been thinking about writing out a thorough comparison between the different tools that exist (Mutalyzer, VV, VEP), as an extension of my previous student's work. That does require a lot more work, though.

Happy to be involved

> Playing the devil's advocate here, considering the last sentence... VV assumes here that I want the C>A variant while I passed G>A and outputs not a correct variant description, but some other variant, that I didn't want 😉
It assumes the position is correct, and my reference base might not be.
Of course, my approach might be the complete opposite here; right now, I'm trying to actively find mistakes in the variants that we store, so I want everything thoroughly checked. Silent conversions of variants are super useful (ins to dup, 3' shifting, etc.), but in this case, it's a problem for me because this is undeniably a different variant - it is a translation of the genotype that I sent.

Problem is though that if you don't tell me where the C>A comes from how can I tell you if it is wrong. I can guess but in many cases C>A will also be right. In fact both can be right at the same time. I can prove it if you like :) . However if the gene/genomic reference sequence is provided then absolutely we can make this assertion.

> Great! Just to be sure, if I'd pass this format for an exonic variant, will still the NM sequence be used rather than the NC sequence? Just to be sure, because Mutalyzer uses the NC sequence for exonic variants in this case, and just uses the NM for the mapping of the given position. If needed, I could add code that checks for intronic positions and chooses the format to send.

Absolutely, we always use the correct reference sequence. Exonic bases are ALWAYS validated against the NM_.

**Comment by PeteCausey-Freeman** [comment]
If you are happy let me know and I'll start coding it up

**Comment by ifokkema** [comment]
> Happy to be involved

Did you personally have other ideas about an approach?


> > Playing the devil's advocate here, considering the last sentence... (...)
> Problem is though that if you don't tell me where the C>A comes from how can I tell you if it is wrong. I can guess but in many cases C>A will also be right. In fact both can be right at the same time. I can prove it if you like :) . However if the gene/genomic reference sequence is provided then absolutely we can make this assertion.

I meant more that you wrote VV doesn't assume, and my point was that it still does, it just assumes something else :wink:


> > Great! Just to be sure, if I'd pass this format for an exonic variant, will still the NM sequence be used rather than the NC sequence? Just to be sure, because Mutalyzer uses the NC sequence for exonic variants in this case, and just uses the NM for the mapping of the given position. If needed, I could add code that checks for intronic positions and chooses the format to send.
> Absolutely, we always use the correct reference sequence. Exonic bases are ALWAYS validated against the NM_.

Excellent! All good then for me to use NCs, if that gets me a reference base error! :+1:

**Comment by ifokkema** [comment]
All required code added to LOVD in [feat/VV 5f8f3039](/LOVDnl/LOVD3/commit/5f8f3039)!

**Comment by PeteCausey-Freeman** [comment]
> Did you personally have other ideas about an approach?
Perhaps we could bounce some ideas. I have a few different approaches that could be less effort. Might be worth a chat.

**Comment by PeteCausey-Freeman** [comment]
OK, 
Code now gives 
```json
{
    "flag": "warning",
    "metadata": {
        "seqrepo_db": "2018-08-21",
        "uta_schema": "uta_20180821",
        "variantvalidator_hgvs_version": "1.2.5.vv1",
        "variantvalidator_version": "1.0.4.dev11+g97aec97"
    },
    "validation_warning_1": {
        "alt_genomic_loci": [],
        "gene_ids": {},
        "gene_symbol": "",
        "genome_context_intronic_sequence": "",
        "hgvs_lrg_transcript_variant": "",
        "hgvs_lrg_variant": "",
        "hgvs_predicted_protein_consequence": {
            "slr": "",
            "tlr": ""
        },
        "hgvs_refseqgene_variant": "",
        "hgvs_transcript_variant": "",
        "primary_assembly_loci": {},
        "reference_sequence_records": "",
        "refseqgene_context_intronic_sequence": "",
        "selected_assembly": "hg19",
        "submitted_variant": "NC_000017.10(NM_007294.3):c.5277+77G>A",
        "transcript_description": "",
        "validation_warnings": [
            "NC_000017.10:g.41208992C>T: Variant reference (C) does not agree with reference sequence (G)"
        ]
    }
}
```

Comments before committing please

**Comment by ifokkema** [comment]
Looks great, thank you!

**Comment by PeteCausey-Freeman** [comment]
OK, give me 10 and I'll put it on the dev server

**Comment by PeteCausey-Freeman** [comment]
Closed by https://github.com/openvar/variantValidator/commit/fb708f7999c9b1c26e8052f797dc13aae8959258

**Comment by ifokkema** [comment]
Works great, thank you! :+1:
