### ISSUE TITLE
REST service batch variant validation

### ISSUE THREAD

**Issue by peq123** [openvar/variantValidator#208]
Hi Pete

Please add expose the batch validation that is available on the website at https://variantvalidator.org/service/validate/batch/ to the REST service. 

Thanks
peq123

**Comment by PeteCausey-Freeman** [comment]
I have a plan for this. Will sort this afternoon

**Comment by PeteCausey-Freeman** [comment]
We have discussed options for future development with @peq123 once his masters project is complete. We need additional expert advice but he has had some fantastic ideas

**Comment by PeteCausey-Freeman** [comment]
This is now handled

**Comment by ifokkema** [comment]
> This is now handled

Out of curiosity, how is this handled? Can we send multiple variants to any endpoint? If you mean separating the variants by a pipe, that conflicts with the HGVS descriptions for methylation-related variants, so how can we prevent issues there?

**Comment by PeteCausey-Freeman** [comment]
I think VV VF and LOVD will accept multiple submissions. Can't remember if gene2transcrip will

**Comment by ifokkema** [comment]
Ah, OK, so using the pipe. So this is related to #206 then, we're currently unable to send in methylation-related variants due to the pipe being used as an internal separator. We currently don't use the batch feature although it could be useful for us when submitting a large number of variants. Either way, currently we just keep the connection open to reduce the overhead of opening and closing the connection which is already an improvement.
