### ISSUE TITLE
Refseq Transcript versions are not up-to-date for build GRCh38

### ISSUE THREAD

**Issue by peq123** [openvar/variantValidator#209]
Hi Pete, 

The example that I have come across is the transcript NM_007294. The transcript version was updated in Aug 2019. The validator is not accepting .4 and expects the previous version for GRCh38.

https://www.ncbi.nlm.nih.gov/nuccore/NM_007294.4

peq123

**Comment by PeteCausey-Freeman** [comment]
Hi,

Absolutely correct. The database we rely on has not been updated since 2018. GRRR. We are very close to completing our own version of this database. We are actually testing it now and as soon as it is available and good to go I will deploy it and update the Repos as well. Sorry for the delay @peq123

**Comment by PeteCausey-Freeman** [comment]
I would recommend looking at the variant in the context of the .3 version of the transcript. VV can map this from the genomic position. I suspect that the changes will be in the UTR

**Comment by PeteCausey-Freeman** [comment]
VVTA has sorted this as of v2.0.0
