### ISSUE TITLE
Exon numbering - Agile project plan

### ISSUE THREAD

**Issue by kjwinfield** [openvar/variantValidator#258]
User story
-----------
![image](https://user-images.githubusercontent.com/71272357/103775604-300bef80-5026-11eb-879d-4d3c8c1dcb7f.png)

## Related Git Issues
Gathering User Requirements: #251 
Gene2Transcripts API: #253

@kwi11iams and I had a discussion with @PeteCausey-Freeman today to make a plan for the project going forwards

## The Plan

1. Use the existing transcript function made by Pete, which returns a dictionary when a gene symbol or transcript ID is input.
2. Write a function to parse this dictionary so that an input of NG_ NC_ NT_ NW_ will return the exon structure 
3. Take a variant as an input and return the exon/intron number for the start and end of the variant

**Comment by PeteCausey-Freeman** [comment]
Very nice post. Thanks

**Comment by PeteCausey-Freeman** [comment]
The instructions for installing from the develop brach are in this thread.

https://github.com/openvar/variantValidator/issues/257

Link up with Naomi about installing on windows. I'd really like feedback in a new issue from you both so I can update the installation manual

**Comment by kwi11iams** [comment]
Update on Progress 
----------------------
Due to difficulties trying to install VariantValidator on either of our laptops by various methods, we had to take a different approach. Instead of installing VariantValidator and integrating our function directly, we have instead written

**Comment by kwi11iams** [comment]
Re-Open Git Issue

**Comment by kwi11iams** [comment]
Update on Project Plan
-------------------------
Unfortunately, both of us had issues trying to install the VariantValidator (VV) package and the accompanying databases onto our laptops. Due to the time constraints of our project, we had to come up with an alternate plan to our previous idea of integrating our function directly into VariantValidator and its databases, and instead create a function that calls VariantValidator's APIs. 

Our function, `exon_numbering.py`, should take an input of a transcript variant, and with this

1. Call the VV endpoint of the API for the given transcript variant. This is used as a check to ensure the variant input is of the correct format. 
2. Call the gene2transcripts VV endpoint, using the transcript ID of the given variant. This is parsed and used to create a dictionary of the exon structure of the given transcript in the variant input. 
3. Determine the exon location of the given variant, for each of the associated aligned transcripts for the input variant's transcript (i.e. NC and NG). 

As discussed in Git Issue #251, the format of the output of this function will be the following. 
`{NC_000: {"start_exon": "1", "end_exon": "1i"}, NC_0000 ....`
Where, in this case `"end_exon": "1i"` indicates the variant ends in the intron directly following exon 1 (i.e. between exon 1 and 2). 

(NB that this output dictionary is slightly adapted to what was discussed because it is no longer being directly integrated into the VV package. It is also simplified for our first iteration creating the module.)

**Comment by kwi11iams** [comment]
Update on Project Progress
------------------------------

## Overview
We have now created a module, `exon_numbering.py`, that contains a function. This function accepts an input of a variant description, defined by a transcript (e.g. NM) using HGVS nomenclature. It then outputs a dictionary, where the keys are the aligned transcripts (i.e. chromosomal, NC,  or genome, NG) respective to the input variant's transcript. The values for each of these keys are also a dictionary, which contains information on the start and end points of the variant. 

### Examples
These examples correspond to the current tests in our automated testing file, `exon_numbering_tests.py`. They are included here to provide a better understanding of the outputs for given inputs to the function. 
#### Exonic Single Nucleotide Variant
Input = `"NM_007294.3:c.1067A>G"`
Output = `{'NC_000017.10': {'start_exon': '14', 'end_exon': '14'}, 'NC_000017.11': {'start_exon': '14', 'end_exon': '14'}, 'NG_005905.2': {'start_exon': '10', 'end_exon': '10'}}`

NB the start and exons are equal for SNV variants. 

#### Intronic Single Nucleotide Variant
Input = `NM_000088.3:c.642+1G>A`
Output = `{'NC_000017.10': {'start_exon': '44i', 'end_exon': '44i'}, 'NC_000017.11': {'start_exon': '44i', 'end_exon': '44i'}, 'NG_007400.1': {'start_exon': '8i', 'end_exon': '8i'}}`

NB if a variant is in an intron, the labelling is composed of the number of the preceding exon and an `i` notation to indicate it is the intron after this exon. 

#### Deletion variant crossing an exon/intron boundary
Input = `NM_000094.3:c.6751-3_6753del`
Output = `{'NC_000003.11': {'start_exon': '32i', 'end_exon': '33'}, 'NC_000003.12': {'start_exon': '32i', 'end_exon': '33'}, 'NG_007065.1': {'start_exon': '85i', 'end_exon': '86'}}`

## Next Steps
There are still some final edits we would like to make to our function to ensure it is complete and of a high standard. 

- Ensure all code is in PEP-8 format
- Add some exception handling. In particular, check the input using the VV variant endpoint, and add an exception if the input variant is identified as the wrong format. 
- Create a relevant Markdown document to fully explain our function

## Future plans for VariantValidator
As outlined in the previous comment of the Updated Project Plan, the aim of creating this function is for it to be adapted and integrated into Variant Validator. 

By incorporating this feature, it will ultimately enable users of VV to easily identify the exon/intron position of their variant for the given transcript. This features also has plans to aid other ongoing VV projects, such as the idea to return SO terms from VV (#257).

---------------------------
This update reflects the current state of the project, on 26/01/21.

**Comment by kjwinfield** [comment]
Update on Project Progress
--------
We have now completed the Next Steps from the previous update (26/01/21)
- Ensured all code is in PEP-8 format, with some code review from @eastgenomics code school
- Added an exception that will be raised if the input variant is identified as the wrong format using the VV variant endpoint.
- Created and updated the markdown ([exon_numbering.md](https://github.com/openvar/variantValidator/blob/exon_numbering/VariantValidator/modules/exon_numbering.md)) to explain the functionality of the [exon_numbering.py](https://github.com/openvar/variantValidator/blob/exon_numbering/VariantValidator/modules/exon_numbering.py) module

We have also updated the [exon_numbering_tests.py](https://github.com/openvar/variantValidator/blob/exon_numbering/VariantValidator/modules/exon_numbering_tests.py) module, so that the tests are now automated with unittest.

---------------------------
This update reflects the current state of the project, on 27/01/21.

**Comment by PeteCausey-Freeman** [comment]
Now embedded into VV. Thanks
