### ISSUE TITLE
Could VV return exon/intron location per transcript

### ISSUE THREAD

**Issue by beboche** [openvar/variantValidator#301]
That would be very nice!

**Comment by leicray** [comment]
Could you clarify what you mean by "_return exon/intron location_"? Do you mean the number of the exon and/or intron where a variant is located? If so, we will not be able to do that because exon and intron numbers are not part of the HGVS variant nomenclature, as I'm sure you know.

**Comment by beboche** [comment]
Thanks for your answer. Indeed this is not part of the HGVS variant nomeclature, but could be part of a dedicated item. Just a suggestion.

**Comment by leicray** [comment]
If we were to introduce this as a "_dedicated item_", we would need to be able to implement it for all genes. Some genes such as the beta globin gene (_HBB_) would be simple because there is one transcription start site, just three exons, and no arguments about how the exons ought to be numbered.

However, many genes have multiple transcript splice variants and some such genes might have multiple transcription start sites, resulting in up-stream exons that are present in some spliced transcripts but not in others. It's not clear how exon numbering could be easily implemented for such genes.

**Comment by ifokkema** [comment]
If David means what I think David means...
@beboche check out the output of:
https://rest.variantvalidator.org/VariantValidator/tools/gene2transcripts/IVD?content-type=application%2Fjson
It produces genomic locations of the exons in each transcript of a given gene. Given that, you should be able to do what you want to do.

**Comment by beboche** [comment]
Hi Ivo,
thanks, then I was wondering if this was possible to match this with the variant description and add the exon numbering to the transcripts specific descriptions of each variant. But I may not be aware of particular cases which prevent this feature fom being implemented.

**Comment by PeteCausey-Freeman** [comment]
https://github.com/openvar/variantValidator/commit/918463175c6564e94b4a7daee70abb69fb437d0c
