### ISSUE TITLE
3'UTR variant description

### ISSUE THREAD

**Issue by jtdendunnen** [openvar/variantValidator#432]
When I tried variant NM_024649.4:c.1779+7A>G (found in a publication), VV returns NM_024649.4:c.*4C>G.  This is not correct, it should be NM_024649.4:c.*7A>G.

VV correctly notices the variant is in the 3'UTR, but wrongly subtracts 3 nucleotides from the c. description, probably because it is assumed tne nucleotides of the stop codon are not numbered.

**Comment by leicray** [comment]
NM_024649.4:c.1779+7A>G is definitely an invalid variant description because c.1779 is not the final nucleotide of an exon. The authors of the publication possibly did mean to present the description NM_024649.4:c.*7A>G but the publication (DOI:10.1167/iovs.05-1334) does not provide any guidance concerning how they decided to describe the variant. Line 6 in Table 1 does indicate that the variant corresponds to dbSNP entry rs8432 which, in turn, does correspond to NM_024649.4:c.*7A>G.

VariantValidator does try to correct variant descriptions that contain errors, but it is not infallible. In this instance, it has probably counted 7 nucleotides in the 3' direction which is c.*4 and then "corrects" the reference sequence from A to C and generates its best guess at a new description.

In fact, VariantValidator is oblivious of the presence of the stop codon immediately 3' to c.1779 but this should probably be corrected in a future release. Mutalyzer and VEP simply do not know what to do with the description NM_024649.4:c.1779+7A>G.

**Comment by Peter-J-Freeman** [comment]
Hi @leicray and @jtdendunnen 

I'm pretty swamped until later this week, but will try get this sorted by mid next week. I want to make a new full release in mid November since @John-F-Wagstaff will be with us again and we can also push out a new VVTA release.

@leicray is correct that does not incorrectly number stop codons. I suspect that the VV logic just needs a tweak. 

> VariantValidator does try to correct variant descriptions that contain errors, but it is not infallible. In this instance, it has probably counted 7 nucleotides in the 3' direction which is c.*4 and then "corrects" the reference sequence from A to C and generates its best guess at a new description.

I agree with this assumption. This is highly likely meant NM_024649.4:c.*7A>G but in my opinion the VV logic is correct. 

NM_024649.4:c.1779+7A>G = 1779 + 7 which maps to position c.*4 (Have I got this correct?). What is not correct however is the output. The output should be "Error - Incorrect Reference Sequence Provided, should be C not A" or something like that. I do not think it is a failure of the software to get to position c.*4 since the question that has been asked of it is 1779 + 7 and it has handled this correctly. The actual query is incorrect. The question should have been 1779 + 10 or more likely 1782 + 7, inferred from @jtdendunnen 's description that the stop codon is not numbered so I assume the authors numbered from base 1 of the stop codon and not base 3 as they should have done had they followed HGVS rules. 

So, my feeling is that VV needs to be updated to shout an error that the presented reference base is incorrect. The authors need to be taught that the final base of the stop codon should have been used in the description.  

For confirmation, VV correctly converts NM_024649.4:c.1782+7A>G into NM_024649.4:c.*7A>G so it really cannot be blamed for not being able to convert NM_024649.4:c.1779+7A>G into NM_024649.4:c.*7A>G because it would be incorrect to do so I feel

**Comment by jtdendunnen** [comment]
Agreed, when a variant description is not correct this should be made very clear. In addition, it is better not to give variant descriptions which are guessed and certainly not when they change the reference nucleotide.

Regarding Mutalyzer, please note the Position Converter does suggest NM_024649.4:c.*7A>G when NM_024649.4:c.1782+7A>G is used as a query.

**Comment by Peter-J-Freeman** [comment]
> NM_024649.4:c.*7A>G when NM_024649.4:c.1782+7A>G is used as a query.

Thanks for confirming my thinking. That's really useful to know and backs up the idea "VV correctly converts NM_024649.4:c.1782+7A>G into NM_024649.4:c.*7A>G so it really cannot be blamed for not being able to convert NM_024649.4:c.1779+7A>G into NM_024649.4:c.*7A>G" since I suspect Mutalyzer would likely agree on the coordinates for NM_024649.4:c.1779+7A>G. 

> Agreed, when a variant description is not correct this should be made very clear. In addition, it is better not to give variant descriptions which are guessed and certainly not when they change the reference nucleotide.

Yes. This is normally the case. Here we have an example of a type of variant which is being processed slightly differetly, so needs to be trapped and the error generated. Will be pretty simple to fix. I'll get it done this week most likely. Might be able to role out a dev build next week.

**Comment by Peter-J-Freeman** [comment]
Will now show

```
        "validation_warnings": [
            "NM_024649.4:c.1779+7A>G auto-mapped to NM_024649.4:c.*4A>G",
            "NM_024649.4:c.*4A>G: Variant reference (A) does not agree with reference sequence (C)"
        ],

```

**Comment by Peter-J-Freeman** [comment]
Fixed. Will push up ASAP
