### ISSUE TITLE
apt-get: command not found when trying to build variantValidation via Docker

### ISSUE THREAD

**Issue by smzt** [openvar/variantValidator#460]
Dear all,
I'm trying to install the variantValidator database via Docker but when executing the commands as stated in the documentation I get an error. Here is the command.
 $ docker-compose build --no-cache 

This is the output.

Building vdb
Sending build context to Docker daemon  12.59MB
Step 1/7 : FROM mysql:5.7
 ---> d410f4167eea
Step 2/7 : ENV MYSQL_RANDOM_ROOT_PASSWORD yes
 ---> Running in 49b6baeaa585
Removing intermediate container 49b6baeaa585
 ---> 1efd2ec3e91b
Step 3/7 : ENV MYSQL_DATABASE validator
 ---> Running in 37a245e84cab
Removing intermediate container 37a245e84cab
 ---> 339d20384779
Step 4/7 : ENV MYSQL_USER vvadmin
 ---> Running in 22e457e716fc
Removing intermediate container 22e457e716fc
 ---> 17a9cd248ecb
Step 5/7 : ENV MYSQL_PASSWORD var1ant
 ---> Running in f79f575023ab
Removing intermediate container f79f575023ab
 ---> d52ba5cb4e51
Step 6/7 : RUN apt-get update && apt-get install -y wget && rm -rf /var/lib/apt/lists/*
 ---> Running in 090c80c2b297
/bin/sh: apt-get: command not found
The command '/bin/sh -c apt-get update && apt-get install -y wget && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 127
ERROR: Service 'vdb' failed to build : Build failed

The server is Ubuntu 22.04. 

Thanks in advance.

Best regards,

Sheila

**Comment by leicray** [comment]
Hi Sheila,

I am not an expert, but the reason that step 6/7 is failing is that the default location for apt-get is /usr/bin rather than /bin/sh

You ought to run the command locate apt-get to find where that executable resides on your system. I'm running Linux Mint which is based on Ubuntu and apt-get is definitely in /usr/bin on my system.

Kind regards,

Raymond
[VariantValidator Logo]
web: www.variantvalidator.org<https://variantvalidator.org/>
Social media: Twitter<https://twitter.com/intent/follow?ref_src=twsrc%5Etfw%7Ctwcamp%5Ebuttonembed%7Ctwterm%5Efollow%7Ctwgr%5EVariantValidatr&screen_name=VariantValidatr> Facebook<https://www.facebook.com/VariantValidator> Buy-us-a-coffee, supporting SWAN UK<https://www.buymeacoffee.com/VariantValidatr>



From: Sheila ***@***.***>
Sent: 20 December 2022 14:14
To: openvar/variantValidator ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [openvar/variantValidator] apt-get: command not found when trying to build variantValidation via Docker (Issue #460)

***CAUTION:*** This email was sent from an EXTERNAL source. Think before clicking links or opening attachments.

Dear all,
I'm trying to install the variantValidator database via Docker but when executing the commands as stated in the documentation I get an error. Here is the command.
$ docker-compose build --no-cache

This is the output.

Building vdb
Sending build context to Docker daemon 12.59MB
Step 1/7 : FROM mysql:5.7
---> d410f4167eea
Step 2/7 : ENV MYSQL_RANDOM_ROOT_PASSWORD yes
---> Running in 49b6baeaa585
Removing intermediate container 49b6baeaa585
---> 1efd2ec3e91b
Step 3/7 : ENV MYSQL_DATABASE validator
---> Running in 37a245e84cab
Removing intermediate container 37a245e84cab
---> 339d20384779
Step 4/7 : ENV MYSQL_USER vvadmin
---> Running in 22e457e716fc
Removing intermediate container 22e457e716fc
---> 17a9cd248ecb
Step 5/7 : ENV MYSQL_PASSWORD var1ant
---> Running in f79f575023ab
Removing intermediate container f79f575023ab
---> d52ba5cb4e51
Step 6/7 : RUN apt-get update && apt-get install -y wget && rm -rf /var/lib/apt/lists/*
---> Running in 090c80c2b297
/bin/sh: apt-get: command not found
The command '/bin/sh -c apt-get update && apt-get install -y wget && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 127
ERROR: Service 'vdb' failed to build : Build failed

The server is Ubuntu 22.04.

Thanks in advance.

Best regards,

Sheila

-

**Comment by ifokkema** [comment]
> I am not an expert, but the reason that step 6/7 is failing is that the default location for apt-get is /usr/bin rather than /bin/sh

`sh` is an interpreter, not a given location. `/bin/sh -c` is another way to get commands executed in a shell. E.g., `/bin/sh -c 'apt-get update'` can be used to update the apt database. Note the quotes, though. Either way, if apt-get isn't found, either the `PATH` variable is messed up, the system is messed up, or the system isn't Ubuntu.

Adding an `echo $PATH` before the `apt-get` command can give an idea where `sh` is looking for `apt-get`.

**Comment by Peter-J-Freeman** [comment]
Hi @smzt . Might be an odd question, but what chip set does your server have. I think I had this issue with the Apple M1 chip set which is an Arm chip set and not intel. 

You need to know because there is a setting that needs to be tweaked for Arm chips. Can you confirm please?

**Comment by Peter-J-Freeman** [comment]
Note: the setting is switched here https://github.com/openvar/variantValidator/blob/master/vdb_docker.df#L1 and is mentioned in the documentation (or at least ought to be).

**Comment by smzt** [comment]
Hi,
Thanks for all the comments.

To check the system architecture I opened the /proc/cpuinfo file. This is the information for one processor.

processor       : 0
vendor_id       : GenuineIntel
cpu family      : 15
model           : 6
model name      : Common KVM processor
stepping        : 1
microcode       : 0x1
cpu MHz         : 2095.076
cache size      : 16384 KB
physical id     : 0
siblings        : 8
core id         : 0
cpu cores       : 8
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx lm constant_tsc nopl xtopology cpuid tsc_known_freq pni cx16 x2apic hypervisor lahf_lm cpuid_fault pti
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips        : 4190.15
clflush size    : 64
cache_alignment : 128
address sizes   : 40 bits physical, 48 bits virtual
power management:

I did not changed the specifications in the configuration file because the default value was set for intel.


Regarding the location of apt-get. I ran the following command:
$ locate apt-get
/snap/core20/1695/usr/share/bash-completion/completions/apt-get
/snap/core20/1695/usr/share/bash-completion/completions/slapt-get
/snap/core20/1738/usr/share/bash-completion/completions/apt-get
/snap/core20/1738/usr/share/bash-completion/completions/slapt-get
/usr/bin/apt-get
/usr/share/bash-completion/completions/apt-get
/usr/share/bash-completion/completions/slapt-get
/usr/share/man/de/man8/apt-get.8.gz
/usr/share/man/fr/man8/apt-get.8.gz
/usr/share/man/it/man8/apt-get.8.gz
/usr/share/man/ja/man8/apt-get.8.gz
/usr/share/man/man8/apt-get.8.gz
/usr/share/man/nl/man8/apt-get.8.gz
/usr/share/man/pt/man8/apt-get.8.gz

Is the command " $ docker-compose build --no-cache" really looking for apt-get in the server or in the image? I tried to add a line in the vdb_docker.df to specify the PATH for apt-get in my system (added ENV PATH="/usr/bin" after the line FROM mysql:5.7)  without any success. 

The OS is Ubuntu 22.04. The system was reset a few weeks back and I have not installed almost anything so I doubt there are inconsistencies in the system already.

Any help would be much appreciated.

Thanks for your help.

Regards,

Sheila

**Comment by leicray** [comment]
Have you tried the command `which apt-get` so that you can be sure that `apt-get` really is defined within your system? If everything is okay, the commend should return something like `/usr/bin/apt-get`. If there is no response (i.e., the prompt simply reappears), then `apt-get` has not been found within the PATH.

As @ifokkema has pointed out, apt-get update needs to be enclosed within single quotes, i.e., `'apt-get update'`. Have you tried that?

**Comment by leicray** [comment]
> Note: the setting is switched here https://github.com/openvar/variantValidator/blob/master/vdb_docker.df#L1 and is mentioned in the documentation (or at least ought to be).

These instructions will only work for Debian-based versions of Linux such as Ubuntu and Linux Mint. Versions such as Fedora and CentOS which are based on RedHat Linux use `yum` to manage packages.

**Comment by Peter-J-Freeman** [comment]
@leicray. The LINUX distribution is whatever gets put into the docker container so the host OS doesn't really matter. Remember, docker is a VM. Docker I think is installing an ubuntu container for the MySQL build. What I noticed during the rebuild is that since apple introduced the Silicone chips, which are ARM based, the Ubuntu based validator database container does not work work with the apt-get command. The only way I could resolve this was to pull a docker container compatible with the ARM chip set and not the LINUX. 

> These instructions will only work for Debian-based versions of Linux such as Ubuntu and Linux Mint. Versions such as Fedora and CentOS which are based on RedHat Linux use yum to manage packages.

So this would be correct if we were not spinning up docker, but the Yum vs Apt-get command is not, I believe, the issue. It is the chip set in the processor. A build of the MySQl container for an Intel chip will not run on an ARM chip. This is why this setting has been introduced. 

What is interesting is that on my Arm based mac, I cannot currently install an Oracle VM distribution of LINUX mint because the Arm chip version of oracle VM is not yet complete. Apple have put the cat amongst the pidgeons by backing Arm. I think this sort of issue will come up more and it is becoming essential for users to know what chip they are using. In this instance, I suspect the the server mentioned by @smzt is running on Arm and not intel, so a re-build of the container is required with the Arm chip version of the MySQL database container selected.

**Comment by ifokkema** [comment]
I'm not an expert on this at all, but while other chipsets require different kernels and drivers, the `apt` system is independent of that. So I reckon Ubuntu should come preinstalled with it. As such, I believe it would make sense to check the `$PATH` available to the script that's trying to invoke `apt-get`.

As far as I understand the syntax for the .df file, I think some debugging could be accomplished by adding:
```
RUN env | grep ^PATH
RUN which dpkg
RUN dpkg -l apt
RUN which apt-get
```
after the ENV lines.

**Comment by smzt** [comment]
> I suspect the the server mentioned by @smzt is running on Arm and not intel, so a re-build of the container is required with the Arm chip version of the MySQL database container selected.

Hi,
You are right, changing the chip version to Arm worked for us. 

Thanks very much for your help!

Best regards.

Sheila

**Comment by Peter-J-Freeman** [comment]
Fantastic. We will try to improve the docs to make this more clear
