### ISSUE TITLE
Mutalyer / VV discrepancy for SHANK3

### ISSUE THREAD

**Issue by beboche** [openvar/variantValidator#475]
**Describe the bug**
Hi,

a [Mobidetails](https://mobidetails.iurc.montp.inserm.fr/MD/) user reports a difference between VV and Mutalyzer for this variant: 

chr22:g.51160326_51160327del - hg19

Mutalyzer reports c.4251_4252del p.Val1419Glyfs*4

while VV reports

c.4290_4291del p.(Val1432GlyfsTer4)

**To Reproduce**

[Mutalyzer](https://mutalyzer.nl/normalizer/GRCh37(Chr22):g.51160326_51160327del)

Who should we believe?

**Comment by ifokkema** [comment]
There's a very long list of such conflicts. Pete and I went and investigated a few. In all cases, Mutalyzer was "wrong". Bear in mind that "wrong" in this case means that the result `NC_000022.10(NM_001372044.2):c.4251_4252del` is *not* equal to `NM_001372044.2:c.4251_4252del`. That is by design, so it isn't wrong; it's just a different decision in the design. They consider it wrong to assume that `NC_000022.10(NM_001372044.2)` in any way equals the positioning system of `NM_001372044.2`, and there will be no agreement on the matter. I can go into more details about the origin of this issue, but in short, it's `NM_001372044.2` not aligning perfectly to `NC_000022.10`. The Mutalyzer team ensures me that the new Mutalyzer3 has a way to get from `NC_000022.10(NM_001372044.2):c.4251_4252del` to the correct description based on `NM_001372044.2`, but I haven't been able to find it. It's likely a multi-step process.

**Comment by beboche** [comment]
thx @ifokkema

**Comment by Peter-J-Freeman** [comment]
What is interesting is that SHANK3 has 3 exons not represented in the genome. What I think may be going on is that VV actually accounts for the missing aligned sequence whereas Mutalyzer overlooks it. VV treats transcripts independantly from the genomie reference sequences. Mutalyzer does not, therefore, when alignments are gapped, mutalyzer cannot compensate for missing sequence. I will look deeper into this ASAP, but this is my guess

**Comment by ifokkema** [comment]
> What is interesting is that SHANK3 has 3 exons not represented in the genome.

Then, that is the issue, indeed!


> What I think may be going on is that VV actually accounts for the missing
> aligned sequence whereas Mutalyzer overlooks it.

Mutalyzer simply never sees it; they check the NC for the NM annotation, but the NC just provides the positions of the exons and positions of the CDS. So Mutalyzer considers the NC sequence *only*, creates the `NC(NM)` mapping using the positions provided in the annotation in the NC, and then applies `c.` positions to it, where `c.1` will start and wherever the NC says the CDS starts. Their `NC(NM):c` positions are therefore *not* compatible with the `NM:c` positions, whereas, in VV, this translation is still possible.


> I will look deeper into this ASAP, but this is my guess

No need! You have already provided the reason :wink:

**Comment by Peter-J-Freeman** [comment]
Excellent 

@beboche , does this provide the answer. Basically, VV compensates for the missing exons in the genome build, Mutalyzer does not.

**Comment by leicray** [comment]
Not surprisingly, there is no MANE Select transcript for _SHANK3_. The currently valid RefSeq transcript is [NM_001372044.2](https://www.ncbi.nlm.nih.gov/nuccore/NM_001372044.2)

Just out of interest, I had a look how Alamut Visual Pro handles this gene. It does not offer NM_001372044.2 as a possible transcript with which to view variants. Instead, it offers [NM_001080420.1](https://www.ncbi.nlm.nih.gov/nuccore/NM_001080420.1?report=genbank) which is described as:

`Record removed. NM_001080420.1: This RefSeq was permanently suppressed because currently there is insufficient support for the transcript and the protein. Exon 11 was based on ab initio prediction and is not supported by transcript data.`

As is normally the case with problematic genes, Alamut Visual Pro also suggests some Ensembl transcripts that are probably equally badly broken.

**Comment by beboche** [comment]
> Excellent
> 
> @beboche , does this provide the answer. Basically, VV compensates for the missing exons in the genome build, Mutalyzer does not.

yes, fine for me, thanks
