### ISSUE TITLE
protein variant unchanged

### ISSUE THREAD

**Issue by jtdendunnen** [openvar/variantValidator#482]
For variant NM_152641.4:c.915_916delinsAC VV reports the consequences at protein level as p.(Leu305=). Is this correct?  Nucleotide 916 affects amino acid 306. Should it not be p.(Leu305_Leu306=)?

**Comment by Peter-J-Freeman** [comment]
Thanks @jtdendunnen. I will look into it

**Comment by leicray** [comment]
That's a tricky one. As far as I can see, the HGVS nomenclature recommendations do not provide explicit guidance on variants such as this with respect to the outcome at the protein level. Mutalyzer says p.(=) and Alamut Visual Plus says p.(Leu305=), as is the case with VariantValidator.

In case I have missed it, can you provide a pointer to what the HGVS nomenclature recommendations say?

**Comment by ifokkema** [comment]
> In case I have missed it, can you provide a pointer to what the HGVS nomenclature recommendations say?

This may be one of those situations where it depends on your interpretation of the guidelines. The [HGVS nomenclature website](https://varnomen.hgvs.org/bg-material/consultation/svd-wg001/) states:
> The proposal suggests to extend the HGVS recommendations to allow description of variant tested but no change detected using the character “=” (equal to); g.50377648=, m.15366=, c.1823=, n.611=, r.377=, p.Val76=. The description should include the position(s) screened (nucleotides or amino acids) and the reference sequence used should always be mentioned.

So the question is whether or not AA 306 was "screened". Since we're talking about protein change predictions, I would argue it was, since the sequence of DNA base 916 was given. Therefore, the AA 306 was internally generated and found to not have been changed (hence, it was screened), which led to VV generating `p.(Leu305=)`.

**Comment by Peter-J-Freeman** [comment]
So is the consensus p.(Leu305=) or p.(Leu305_Leu306=).

I'm suspecting we should be outputting p.(Leu305_Leu306=) but want to confirm please @ifokkema @jtdendunnen @ifokkema

**Comment by Peter-J-Freeman** [comment]
This is now fixed. We are now handling internally rather than using the hgvs.py library

Will push up once tests complete after a big day of debugging.
